package cz.codes;

import java.text.Normalizer;

public class SpecCharToACSII {

	public static void main(String[] args) {
		
		final String[] input = {"Andrlova Katerina",
				"Anikienko Valeria",
				"Balážová Lucia",
				"Barden Christian",
				"blokovaný přístroj - gmail",
				"Boiko Nataliia",
				"Bošková Petra",
				"Božaca Anna",
				"brigáda IoT1",
				"Čechová Michaela",
				"Dalquen Carsten",
				"David Jiří",
				"Dohányos Vojtech",
				"Duda Václav",
				"Dušek Martin",
				"Dvořák Radek",
				"Erdenebat Temuulen",
				"Fedorko Michal",
				"Felio Montes Jose Francisco",
				"Fialová Hana",
				"Fidelman Andrei",
				"Filipová Jana",
				"Fleková Klára",
				"Gabrielová Bára",
				"Gottvald Jiří",
				"Gutierrez Tereza",
				"Hanzelyová Anna",
				"Havlíčková Kristína",
				"Hejsek Jakub",
				"Hlaváčová Hupková Martina",
				"Holík David",
				"Hönigschmied Ivo",
				"Hrdličková Monika",
				"Hronková Judita",
				"Chalupová Andrea",
				"Ivanigová Petra",
				"Käding Jan",
				"Káninská Eva",
				"Karbanová Natália",
				"Knaifl Tomáš",
				"Kopáčková Macháčková Kristýna",
				"Kortus Martin",
				"Kostyk Roman",
				"Kot Tetiana",
				"Kozlová Lucie",
				"Krasnova Kateřina",
				"Krausová Adéla",
				"Kročko Ján",
				"Krulich Barbara",
				"Křiváková Lucie",
				"Kubelková Kateřina",
				"Lazar Petr",
				"Macků Magdaléna",
				"Malochová Markéta",
				"Mařík Jan",
				"Maslov Andrey",
				"Medvedev Kirill",
				"Meijer Klaas-Jan",
				"Meravý Vilém",
				"Michalcová Lenka",
				"Nebřenský Daniel",
				"Nejtek David",
				"Neuman Ondřej",
				"Novák David",
				"Nováková Anna",
				"Ordonez Camila",
				"Paličková Barbora",
				"Pavlíčková Adéla",
				"Pechová Junková Eliška",
				"Pilát Matej",
				"Plajner Jan",
				"Pohl Ondřej",
				"Poledňáková Anna",
				"Procházka Mikuláš",
				"Pustina Pavel",
				"Rathan Bohumil",
				"Recepce",
				"Rochovanská Michaela",
				"Rosoľanková Beáta",
				"Ryšánek Jan",
				"Slabá Kristýna",
				"Stránský Michal",
				"Sýkora Tomáš",
				"Šavrdová Hana",
				"Škývarová Helena",
				"Šmidt Jan",
				"Špalová Magdaléna",
				"Trnková Jaroslava",
				"Tyčiaková Nikola",
				"týmový pro KB",
				"Ullmann Petr",
				"Urbánková Šárka",
				"Vachata Vladislav",
				"Vais Očenášová Nikola",
				"Valc Pavel",
				"Vavroušek Martin",
				"Vlčková Kateřina",
				"volný přístroj",
				"volný přístroj",
				"volný přístroj",
				"volný přístroj",
				"volný přístroj",
				"volný přístroj",
				"volný přístroj",
				"volný přístroj",
				"volný přístroj",
				"volný přístroj",
				"volný přístroj",
				"volný přístroj",
				"volný přístroj",
				"volný přstroj",
				"Votavová Veronika",
				"Weidenborner William",
				"Yachtbus",
				"Zajíc Stanislav",
				"Zasadil Jan",
				"Zeman Filip"};
		
		for (String vstup : input)
				System.out.println(Normalizer.normalize(vstup, Normalizer.Form.NFD).replaceAll("[^\\p{ASCII}]", "")
		);

	}

}
